In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#split input and output
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [6]:
#split training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_train
x_test=sc.fit_transform(x_test)
x_test

array([[ 0.94974655, -0.04448183, -0.10502969,  0.91412058, -0.51395617],
       [ 0.5955739 , -0.18856306, -0.10502969, -1.09394758, -0.51395617],
       [ 0.66640843,  1.75479764,  0.72285141,  0.91412058,  1.94569121],
       ...,
       [ 1.16225013,  1.35814027, -0.93291079,  0.91412058, -0.51395617],
       [ 1.79976089,  1.5109011 , -0.10502969,  0.91412058, -0.51395617],
       [ 1.65809183, -0.94715942, -0.93291079, -1.09394758, -0.51395617]])

In [38]:
# Model creation
from sklearn.svm import SVR
regressor=SVR(kernel="linear",C=1.0,gamma="auto")
regressor.fit(x_train,y_train)
regressor

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [39]:
regressor.n_support_

array([  753659127, -1066066004])

In [40]:
regressor.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935])

In [41]:
regressor.intercept_

array([9445.22978805])

In [42]:
y_pred=regressor.predict(x_test)
y_pred

array([ 9648.19080571,  9448.42998185, 10804.39696837,  9999.38779362,
        9444.71530276,  8949.60088903,  8446.79696476,  9694.86064998,
        9209.16404281,  9016.78823629,  8968.32855899,  9538.99135795,
        9322.83864302,  8917.59269896,  9952.51909243,  9581.42253063,
        9828.67117461,  8820.50919977,  9204.57179618,  9745.07833059,
       10747.68837549,  9809.78676459,  9603.30870891, 10571.79146962,
        8678.89271466,  9064.26051617,  8685.18928829,  9301.94871248,
        8866.23309674,  9445.58453211,  9259.64017203, 11146.33749417,
       10022.46625756,  9792.59509783,  9747.9682533 ,  8855.03243651,
        9553.62364978, 10086.1543139 , 10438.21872244,  8580.7612927 ,
        8971.95629522,  8850.5528199 , 10324.38492558, 11095.94491756,
        9712.07850165,  8654.14849124,  9578.18312962,  9283.06918815,
        8819.66890314,  9722.50479832,  8694.21941647,  8565.51116415,
       10657.66689957, 10863.2546476 ,  9907.82333515,  8891.42798498,
        8825.88373289,  9522.20234805,  9401.5133651 ,  9852.05859591,
        8531.02822564, 11190.44284253,  9985.11930174,  9626.79559047,
        9640.81284573,  9678.66378964,  9708.10970778, 10211.29376932,
        8548.22989461,  9332.59707757,  9871.33645766,  9789.49833345,
        9711.84992933, 10021.64503615,  9797.75278708,  9832.25731601,
        9351.06306776,  9414.80022032, 10245.86162373, 11164.22328596,
        9713.5865157 , 10621.32411261,  8662.59754595,  9419.30128264,
       10562.49629528, 10196.77108466,  8889.66867068,  8783.13345594,
        9850.5761387 , 10117.36589583,  9081.04952607,  9719.95398429,
        8823.0301519 ,  9391.30319185,  9080.15856606,  8979.25394816,
       10889.52594591, 10571.85631441,  8982.06607902,  9854.7427012 ,
        8699.71341426,  9160.55000042,  8886.17925164, 10305.01667658,
       10511.29379606,  8693.52319778,  9676.08482737,  8856.7793781 ,
        9866.78775481, 11073.78007794,  9646.54505062,  9089.83661556,
        9476.31846547,  9689.93942719, 11090.65869061,  9304.59149977,
        8521.34449338,  9524.06745772,  9944.81325896,  9455.04271491,
       10619.18566823,  9480.21147056, 10082.32018452,  9046.57090701,
        9331.97786625,  8793.57183409, 10578.4419857 , 10532.846259  ,
       11143.47628147,  8676.52678445,  9378.04109461,  8571.48612278,
        9167.10105624,  9515.73354824, 10457.72119189, 10203.98625889,
       10405.10546641,  9512.68349521, 10742.77889555,  8672.05572874,
        8567.21470667,  9697.81807739,  9645.24035765,  9715.47753524,
        9011.2230586 , 10045.70513675,  9910.99904326,  8626.29001423,
        8462.85355895,  9667.05823417,  9133.48000031, 10086.31617047,
        9636.10667247,  8534.77291134,  8633.44056638,  9223.85966013,
        8678.52452856,  8528.29410932,  9581.02987596,  9539.82021107,
        8900.91510049, 10047.30166529,  9815.47132896,  9708.74778601,
        8847.69016589,  8836.46511509,  9596.05904953,  8983.07218426,
        8928.98098092,  8579.36699696,  8883.12300821,  8855.20544717,
        9353.93191217,  8764.80592764,  8878.48470259,  8869.45810939,
        8811.37536988,  9141.14360098, 11082.08922945,  8473.05257811,
        9658.47654502,  9211.11414639,  9825.69625799,  8841.3054308 ,
        9006.63383481, 11079.24816587,  8658.86732661,  8569.1142871 ,
       10016.20695484,  9576.23446735, 10737.22408747,  8790.54783564,
        9054.68365318, 10599.13688551,  8795.19758477,  8666.0532787 ,
        9177.4686219 ,  9105.35503584,  8989.11069108,  8945.76696797,
        9706.08145933, 11215.17576715,  9766.8301581 , 10127.95281609,
        8934.53169226, 10681.56291782,  8737.52628573,  9663.08721452,
        9143.14358345,  8638.80192974,  9538.01116259,  9938.68673538,
        8843.94426159,  8679.83843926,  9274.76435609,  8642.49399864,
        9145.77622384,  8919.62952269,  9872.46965927,  9026.25066054,
        9154.83952618,  9173.78604308,  9453.12737151,  8647.70984274,
        9821.34114457, 10092.82052933,  9846.00915769,  9743.79184769,
        9148.05399259,  8698.16279999,  8512.46529038,  9542.55576869,
        9874.65401792,  8589.77205624,  8901.80281494,  9331.52742415,
        9461.39758809,  9879.60256311,  9169.06116202,  9612.8404421 ,
        9113.38106186,  9863.73344594,  9351.50689792,  9252.13633426,
        9399.84472747,  9690.31302103,  8614.19271124,  9368.77923915,
        8546.81666835,  9227.05681396, 10044.70333658, 11184.63988738,
        8832.56188509,  8854.31974838,  8474.77360983,  8442.27826852,
        9453.65856607,  8550.21238788,  8801.08711537,  8733.99109712,
        9369.3849133 , 10691.01663646, 11131.47123668,  9973.3383651 ,
        9270.88689125,  9887.24487716, 10196.21881179,  9445.71716655,
       10428.02546404,  8554.5775035 ,  9920.5789147 ,  9066.68999457,
        9837.80802735,  8727.12410459, 10335.96270023,  9061.43694179,
        9668.79070941,  9455.03256799,  8623.38562516,  9866.933559  ,
        9763.13009008,  9091.34922409,  9880.89424542,  8484.09915819,
        9257.65387143,  8771.24996948,  9328.98265581, 10439.254979  ,
        8958.33098815,  8466.52469426,  8498.43774351, 11136.93695411,
        9507.29593704,  8957.74610289,  9774.29059679,  9739.71251746,
        9822.07181964,  9200.2022164 ,  9095.2611597 ,  9618.30457799,
        8549.58115869,  8634.35534259,  9827.50068322,  9887.5869943 ,
        9920.91911166,  8702.87465601,  8757.13771811,  9439.57193516,
        9654.74330283,  9562.96789156, 10205.83107474,  9130.97575291,
        9635.82533684,  8520.52788083,  9345.21139819,  9075.59395555,
        9375.46990875,  8477.17530741,  9289.58260564, 10582.85395737,
        8705.49809125,  8824.15442521,  8442.19327461,  9496.61387596,
        8896.93832009,  9719.93807662, 11209.65715609, 10043.30126442,
        9561.38411752, 10616.31445333,  9847.14804207,  8938.2619116 ,
        9613.82352007,  8814.44198293, 11041.74281045,  8960.1120331 ,
        9810.86763882,  8514.16854349,  9655.45807023,  8668.28513317,
       10872.16529851,  9285.47197221,  8644.99717214,  9956.87500291,
        8954.34930947,  9034.24114189, 11120.24898602,  8547.71604902,
        9372.80063723,  8563.71658202,  9632.21208136,  8667.8187834 ,
        9200.11442235,  8989.04699818, 10857.70091342,  9393.24753467,
       10193.46130081,  9901.9392615 ,  9171.46617186,  9376.55978929,
        8522.53706845,  8719.34024218,  8568.23527826,  9580.90868504,
       10938.2049778 ,  9724.48951738,  8463.64203584,  9799.70289066,
        8637.2154034 ,  9396.26060174,  8884.10018072,  8791.49644285,
        8787.72253501,  9773.92844647,  9082.40711267,  8392.56153877,
       10387.01780924,  9770.53274133, 10807.31280096,  9753.26147399,
        9029.75598724,  8563.80581738,  8538.30550675,  9591.80341076,
        9061.88551294,  8501.81770008,  9625.76357537,  9187.46987242,
        9265.42434137,  8785.00158845,  8628.00802311, 10188.68165516,
        8621.50604913,  9486.13036801,  8563.16999191,  9402.29212921,
        9847.87124452,  8931.15965682,  9822.39193109,  9802.21513719,
       10128.52749083,  9872.62258753])

In [43]:
#validation
from sklearn.metrics import r2_score
r2_score=r2_score(y_pred,y_test)
r2_score

-337.97953502806143